defaults:
  - model: gpt
  - slurm: default
  - _self_


attractor:
  name: Lorenz
  driven_noise: 0.0
  dt: 0.01
  observed_noise: 0.05
  dim_observed: 0
  resample: True
  # timescale: 0.01 #if resample is False, we need to pick this. TODO: implement

data:
  time: 100
  nsamples: 100
  batch_size: 32

train:
  optimizer: AdamW
  lr: 0.01
  weight_decay: 0.01
  epochs: 2000
  loss: MSE
  nsteps: 1 #train on nstep prediction
  eval_nsteps: 100
  schedule: True

eval: 
  nsteps: 5
  metrics: [ 
    compute_all_pred_stats,
    compute_dynamic_quantities,
    neighbors_comparison,
    # gp_diff_asym,
    predict_hidden_dims_lm,
    predict_hidden_dims_mlp,
    # dsa
    ]
  neighbors_comparison:
    n_neighbors: 25
  dyn_quants:
    traj_length: 100
    ntrajs: 10
    rtol: 1e-3
    atol: 1e-10
  predict_hiddens:
    linear_model_kwargs:
      l1_ratio: 0.0 
      alpha: 1e-1 
      max_iter: 2000
    mlp_kwargs:
      hidden_layer_sizes: [300]
      alpha: 1e-4
      max_iter: 2000

  dsa:
    n_delays: [10,10]
    rank: 30
    pca_dim:  #blank if none
    delay_interval: 1
    lr: 5e-3
    iters: 1500
    device: cuda
    
job:
  chdir: True


