defaults:
  - model: mamba
  # - slurm: default
  - _self_


attractor:
  name: Lorenz
  driven_noise: 0.0
  observed_noise: 0.00
  dim_observed: 0
  resample: True
  timescale: 0.01 #if resample is False, we need to pick this. TODO: implement

data:
  time: 100
  nsamples: 200
  batch_size: 32

train:
  optimizer: AdamW
  lr: 0.005
  weight_decay: 0.001
  epochs: 200
  loss: nn.MSELoss
  nsteps: [1] #train on nstep prediction

metrics: 
  dyn: [KY,correl,autocorrel,MI,maxLE]
  pred: [MSE, MASE]