defaults:
  - model: lru
  # - slurm: default
  - _self_


attractor:
  name: Lorenz
  driven_noise: 0.0
  dt: 0.01
  observed_noise: 0.00
  dim_observed: 0
  resample: False
  # timescale: 0.01 #if resample is False, we need to pick this. TODO: implement

data:
  time: 100
  nsamples: 1000
  batch_size: 32

train:
  optimizer: AdamW
  lr: 0.005
  weight_decay: 0.001
  epochs: 300
  loss: nn.MSELoss
  nsteps: [1,2,3,5,10] #train on nstep prediction
  eval_nsteps: 500

eval: 
  metrics: [ #TODO: use this
    compute_all_pred_stats,
    compute_dynamic_quantities,
    neighbors_comparison,
    gp_diff_asym,
    predict_hidden_dims
    dsa
    ]
  neighbors_comparison:
    n_neighbors: 100
  dyn_quants:
    traj_length: 1000
    ntrajs: 10
    rtol: 1e-3
    atol: 1e-10
  predict_hiddens:
    model_kwargs:
      l1_ratio: 0.5 
      alpha: 1e-1 #TODO: figure out elasticnetCV
  dsa:
    n_delays: [10,1]
    rank: 30
    delay_interval: 1
    lr: 5e-3
    iters: 1500
    device: cuda


    


