defaults:
  - model: gpt
  - slurm: default
  - _self_


attractor:
  name: Lorenz
  driven_noise: 0.0
  dt: 0.01
  observed_noise: 0.00
  dim_observed: 0
  resample: False
  # timescale: 0.01 #if resample is False, we need to pick this. TODO: implement

data:
  time: 1000
  nsamples: 100
  batch_size: 32

train:
  optimizer: AdamW
  lr: 0.01
  weight_decay: 0.01
  epochs: 2000
  loss: MSE
  nsteps: 1 #train on nstep prediction
  eval_nsteps: 100
  schedule: True

eval: 
  metrics: [ #TODO: use this
    compute_all_pred_stats,
    compute_dynamic_quantities,
    neighbors_comparison,
    gp_diff_asym,
    predict_hidden_dims
    dsa
    ]
  neighbors_comparison:
    n_neighbors: 25
  dyn_quants:
    traj_length: 1000
    ntrajs: 10
    rtol: 1e-3
    atol: 1e-10
  predict_hiddens:
    model_kwargs:
      l1_ratio: 0.5 
      alpha: 1e-1 #TODO: figure out elasticnetCV
      max_iter: 2000

  dsa:
    n_delays: [100,10]
    rank: 100
    delay_interval: 1
    lr: 5e-3
    iters: 1500
    device: cuda
    
job:
  chdir: True


